language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script:
  - wget -O pdf.tar.bz2 http://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.11.0_rc1-static-amd64.tar.bz2
  - tar -xf pdf.tar.bz2
  - rm -f pdf.tar.bz2
  - sudo mv wkhtmltopdf-amd64 /usr/local/bin/wkhtmltopdf
  - sudo chmod a+x /usr/local/bin/wkhtmltopdf
  - composer install --dev
script: vendor/bin/atoum -c .atoum.travis.php
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover .atoum.coverage.xml
